import { NextResponse } from 'next/server';
import { requireUser } from '@/lib/session';
import { prisma } from '@/lib/prisma';
import { secureWhere, includeCommon } from '@/lib/data';
import { priorityLabels, statusLabels, visibilityLabels } from '@/components/AdminForms';
const map:any={tasks:['task',true,false],events:['event',true,false],incidents:['incident',false,false],projects:['project',false,true]};
function csv(rows:any[]){ const head=['id','titulo','descripcion','area','responsable','prioridad','estado','fecha_limite','visibilidad','creado']; return [head.join(','),...rows.map(r=>[r.id,r.title??r.name,r.description,r.area?.name,r.responsible?.name,(priorityLabels as Record<string,string>)[r.priority]??r.priority,(statusLabels as Record<string,string>)[r.status]??r.status,r.dueDate??r.expectedEndDate??'',(visibilityLabels as Record<string,string>)[r.visibility]??r.visibility,r.createdAt].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','))].join('\n') }
function filters(url: URL) { const where: any = {}; const q = url.searchParams.get('q'); if (url.searchParams.get('status')) where.status = url.searchParams.get('status'); if (url.searchParams.get('priority')) where.priority = url.searchParams.get('priority'); if (url.searchParams.get('area')) where.areaId = url.searchParams.get('area'); if (url.searchParams.get('responsible')) where.responsibleId = url.searchParams.get('responsible'); if (q) where.OR = [{ title: { contains: q, mode: 'insensitive' } }, { description: { contains: q, mode: 'insensitive' } }]; return where; }
export async function GET(request:Request,{params}:{params:{entity:string}}){ const cfg=map[params.entity]; if(!cfg) return NextResponse.json({error:'Entidad no soportada'},{status:404}); const user=await requireUser(); const rows=await (prisma as any)[cfg[0]].findMany({where:{AND:[secureWhere(user,cfg[1],cfg[2]),filters(new URL(request.url))]},include:includeCommon,take:1000}); return new NextResponse(csv(rows),{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="${params.entity}.csv"`}}); }
