import Link from 'next/link';
import { Shell } from '@/components/Shell';
import { requireUser } from '@/lib/session';
import { prisma } from '@/lib/prisma';
import { secureWhere } from '@/lib/data';
import { saveIncident } from '@/lib/actions';
import { Filters, Select, Text, TextArea, areaOptions, incidentCategories, priorities, priorityLabels, statusLabels, statuses, userOptions } from '@/components/AdminForms';

function dateTimeValue(value?: Date | null) { if (!value) return ''; return new Date(value.getTime() - value.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function short(text?: string | null) { if (!text) return '—'; return text.length > 120 ? `${text.slice(0, 120)}…` : text; }
function filteredHref(base: string, searchParams: Record<string, string | undefined>) { const params = new URLSearchParams(); for (const key of ['q', 'area', 'status', 'priority', 'responsible']) if (searchParams[key]) params.set(key, searchParams[key]!); const query = params.toString(); return `${base}${query ? `?${query}` : ''}`; }

export default async function Page({ searchParams }: { searchParams: Record<string, string | undefined> }) {
  const user = await requireUser();
  const [areas, users] = await Promise.all([prisma.area.findMany({ where: { active: true }, orderBy: { name: 'asc' } }), prisma.user.findMany({ where: { active: true }, orderBy: { name: 'asc' } })]);
  const where: any = { ...secureWhere(user, false, false) };
  if (searchParams.status) where.status = searchParams.status; if (searchParams.priority) where.priority = searchParams.priority; if (searchParams.area) where.areaId = searchParams.area; if (searchParams.responsible) where.responsibleId = searchParams.responsible; if (searchParams.q) where.title = { contains: searchParams.q, mode: 'insensitive' };
  const rows = await prisma.incident.findMany({ where, include: { area: true, responsible: true, comments: { include: { author: true }, take: 3 } }, orderBy: { updatedAt: 'desc' }, take: 100 });
  const form = (r?: any) => <form action={saveIncident} className="card grid gap-3 md:grid-cols-2">{r && <input type="hidden" name="id" value={r.id} />}<Text name="title" label="Título" value={r?.title} required /><Select name="category" label="Categoría" options={incidentCategories} value={r?.category} /><TextArea name="description" label="Descripción" value={r?.description} /><Select name="areaId" label="Área afectada" options={areaOptions(areas)} value={r?.areaId} /><Select name="responsibleId" label="Responsable" options={userOptions(users)} value={r?.responsibleId} /><Select name="priority" label="Prioridad" options={priorities} value={r?.priority} /><Select name="status" label="Estado" options={statuses} value={r?.status} /><TextArea name="actions" label="Acciones realizadas" value={r?.actions} /><Text name="detectedAt" label="Fecha detección" type="datetime-local" value={dateTimeValue(r?.detectedAt)} /><Text name="resolvedAt" label="Fecha resolución" type="datetime-local" value={dateTimeValue(r?.resolvedAt)} /><TextArea name="comment" label="Comentarios" /><div className="flex gap-2 md:col-span-2"><a className="btn" href="/incidents">Cancelar</a><button className="btn">Guardar incidencia</button></div></form>;
  return <Shell><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-3xl font-bold">Incidencias</h2><div className="flex flex-wrap gap-2"><Link className="btn" href="#new">Nueva incidencia</Link><a className="btn" href={filteredHref('/api/export/incidents', searchParams)}>Exportar CSV</a><a className="btn" href={filteredHref('/api/pdf/incidents', searchParams)}>Generar PDF</a></div></div><Filters areas={areas} users={users} values={searchParams} /><div className="card overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="py-2">Incidencia</th><th>Categoría</th><th>Área afectada</th><th>Responsable</th><th>Estado</th><th>Prioridad</th><th>Fecha detección</th><th>Acciones</th></tr></thead><tbody>{rows.map((r) => <tr className="border-b align-top last:border-0" key={r.id}><td className="max-w-sm py-3"><b>{r.title}</b><p className="mt-1 text-slate-600">{short(r.description)}</p></td><td>{r.category}</td><td>{r.area?.name ?? 'Sin área'}</td><td>{r.responsible?.name ?? 'Sin responsable'}</td><td>{statusLabels[r.status]}</td><td>{priorityLabels[r.priority]}</td><td>{r.detectedAt.toLocaleDateString('es-ES')}</td><td className="min-w-48 space-y-2"><Link className="btn inline-block" href={`/incidents?detail=${r.id}`}>Ver detalle</Link><a className="btn inline-block" href={`/api/pdf/incidents/${r.id}`}>Generar PDF individual</a><details><summary className="btn cursor-pointer">Editar</summary>{form(r)}</details></td></tr>)}</tbody></table></div><details id="new" className="card"><summary className="cursor-pointer font-semibold">Nueva incidencia</summary><div className="mt-3">{form()}</div></details></Shell>;
}
