import Link from 'next/link';
import { Shell } from '@/components/Shell';
import { requireUser } from '@/lib/session';
import { prisma } from '@/lib/prisma';
import { secureWhere } from '@/lib/data';
import { PriorityBadge, StatusBadge } from '@/components/Badges';
function Stat({label,value}:{label:string;value:number}){return <div className="card"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
function Empty(){return <p className="mt-2 text-sm text-slate-500">Sin registros visibles.</p>}
export default async function Home(){const user=await requireUser();const now=new Date();const active={status:{notIn:['COMPLETADA','CANCELADA']}} as const;const [my,overdue,critical,openIncidents,criticalIncidents,eventsCount,projectsCount,nextTasks,nextIncidents,nextEvents,projects]=await Promise.all([
 prisma.task.count({where:{AND:[secureWhere(user,true),active,{OR:[{responsibleId:user.id},{assignees:{some:{userId:user.id}}}]}]} as any}),
 prisma.task.count({where:{AND:[secureWhere(user,true),active,{dueDate:{lt:now}}]} as any}),
 prisma.task.count({where:{AND:[secureWhere(user,true),active,{priority:'CRITICA'}]} as any}),
 prisma.incident.count({where:{AND:[secureWhere(user),active]} as any}),
 prisma.incident.count({where:{AND:[secureWhere(user),active,{priority:'CRITICA'}]} as any}),
 prisma.event.count({where:{AND:[secureWhere(user,true),{startAt:{gte:now}}]} as any}),
 prisma.project.count({where:{AND:[secureWhere(user,false,true),{status:'EN_CURSO'}]} as any}),
 prisma.task.findMany({where:{AND:[secureWhere(user,true),active,{dueDate:{gte:now}}]} as any,include:{area:true,responsible:true},orderBy:{dueDate:'asc'},take:5}),
 prisma.incident.findMany({where:{AND:[secureWhere(user),active]} as any,include:{area:true,responsible:true},orderBy:{detectedAt:'desc'},take:5}),
 prisma.event.findMany({where:{AND:[secureWhere(user,true),{startAt:{gte:now}}]} as any,include:{area:true,responsible:true},orderBy:{startAt:'asc'},take:5}),
 prisma.project.findMany({where:{AND:[secureWhere(user,false,true),{status:'EN_CURSO'}]} as any,include:{area:true,responsible:true},orderBy:{updatedAt:'desc'},take:5})]);
 return <Shell><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-3xl font-bold">Inicio</h2><div className="flex flex-wrap gap-2"><Link className="btn" href="/tasks#new">Nueva tarea</Link><Link className="btn" href="/incidents#new">Nueva incidencia</Link><Link className="btn" href="/events#new">Nuevo evento</Link><Link className="btn" href="/projects#new">Nuevo proyecto</Link></div></div><div className="grid gap-4 md:grid-cols-4"><Stat label="Mis tareas pendientes" value={my}/><Stat label="Tareas vencidas" value={overdue}/><Stat label="Tareas críticas" value={critical}/><Stat label="Incidencias abiertas" value={openIncidents}/><Stat label="Incidencias críticas" value={criticalIncidents}/><Stat label="Eventos próximos" value={eventsCount}/><Stat label="Proyectos activos" value={projectsCount}/></div><section className="grid gap-4 xl:grid-cols-2"><div className="card"><h3 className="font-semibold">Próximas 5 tareas con fecha límite</h3>{nextTasks.length?nextTasks.map(t=><p className="mt-3 text-sm" key={t.id}><Link className="font-medium" href={`/tasks?detail=${t.id}`}>{t.title}</Link> · {t.dueDate?.toLocaleDateString('es-ES')??'—'} · <StatusBadge value={t.status}/> <PriorityBadge value={t.priority}/></p>):<Empty/>}</div><div className="card"><h3 className="font-semibold">Próximas 5 incidencias abiertas</h3>{nextIncidents.length?nextIncidents.map(i=><p className="mt-3 text-sm" key={i.id}><Link className="font-medium" href={`/incidents?detail=${i.id}`}>{i.title}</Link> · {i.area?.name??'Sin área'} · <StatusBadge value={i.status}/> <PriorityBadge value={i.priority}/></p>):<Empty/>}</div><div className="card"><h3 className="font-semibold">Próximos 5 eventos</h3>{nextEvents.length?nextEvents.map(e=><p className="mt-3 text-sm" key={e.id}><Link className="font-medium" href={`/events?detail=${e.id}`}>{e.title}</Link> · {e.startAt.toLocaleString('es-ES')} · {e.area?.name??'Sin área'}</p>):<Empty/>}</div><div className="card"><h3 className="font-semibold">Proyectos activos principales</h3>{projects.length?projects.map(p=><p className="mt-3 text-sm" key={p.id}><Link className="font-medium" href={`/projects?detail=${p.id}`}>{p.name}</Link> · {p.area?.name??'Sin área'} · <PriorityBadge value={p.priority}/></p>):<Empty/>}</div></section></Shell>}
