ALTER TABLE "Area" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Area" ADD COLUMN IF NOT EXISTS "active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Area" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
