import { notFound } from 'next/navigation';
import { requireUser } from '@/lib/session';
import { prisma } from '@/lib/prisma';
import { secureWhere } from '@/lib/data';
import { formatDate, labelPriority, labelStatus, labelVisibility } from '@/lib/print';

export default async function TaskPrint({ params }: { params: { id: string } }) {
  const user = await requireUser();
  const task: any = await prisma.task.findFirst({ where: { AND: [{ id: params.id }, secureWhere(user, true, false) as any] }, include: { area: true, responsible: true, project: true, assignees: { include: { user: true } }, comments: { include: { author: true }, orderBy: { createdAt: 'desc' } } } });
  if (!task) notFound();
  const audits = await prisma.auditLog.findMany({ where: { entityType: 'TASK', entityId: task.id }, include: { user: true }, orderBy: { createdAt: 'desc' } });
  return <main className="mx-auto max-w-4xl bg-white p-8 text-slate-900 print:p-0"><button className="btn mb-6 print:hidden">Imprimir / Guardar como PDF</button><script dangerouslySetInnerHTML={{__html:"document.querySelector('button')?.addEventListener('click',()=>window.print())"}} /><header className="border-b pb-4"><h1 className="text-3xl font-bold">FarmaHub360</h1><p>Gestión interna del Servicio de Farmacia</p><p className="mt-2 text-xl font-semibold">Informe de tarea</p><p>Fecha de generación: {formatDate(new Date(), true)}</p></header><section className="mt-6 grid gap-3"><h2 className="text-2xl font-bold">{task.title}</h2><p><b>Descripción:</b> {task.description ?? '—'}</p><p><b>Área:</b> {task.area?.name ?? '—'}</p><p><b>Responsable:</b> {task.responsible?.name ?? '—'}</p><p><b>Usuarios asignados:</b> {task.assignees.map((a: any) => a.user.name).join(', ') || '—'}</p><p><b>Estado:</b> {labelStatus(task.status)}</p><p><b>Prioridad:</b> {labelPriority(task.priority)}</p><p><b>Fecha límite:</b> {formatDate(task.dueDate, true)}</p><p><b>Proyecto asociado:</b> {task.project?.name ?? '—'}</p><p><b>Visibilidad:</b> {labelVisibility(task.visibility)}</p></section><section className="mt-6"><h3 className="text-xl font-bold">Comentarios</h3>{task.comments.length ? task.comments.map((c: any) => <p className="mt-2" key={c.id}>{formatDate(c.createdAt, true)} · {c.author.name}: {c.text}</p>) : <p>—</p>}</section><section className="mt-6"><h3 className="text-xl font-bold">Historial de cambios</h3>{audits.length ? audits.map((a) => <p className="mt-2" key={a.id}>{formatDate(a.createdAt, true)} · {a.user?.name ?? 'Sistema'} · {a.action} · {a.summary}</p>) : <p>—</p>}</section><footer className="mt-10 border-t pt-4 text-sm"><p>FarmaHub360 · Desarrollado por Ramón Morillo · 2026</p><p>Documento de gestión interna. La identificación del paciente, si procede, debe realizarse en el sistema corporativo autorizado.</p></footer></main>;
}
