CREATE TYPE "TaskType" AS ENUM ('GESTION_INTERNA', 'ORGANIZATIVA', 'DOCENCIA', 'INVESTIGACION', 'CALIDAD_SEGURIDAD', 'INCIDENCIA_CIRCUITO', 'PACIENTE_ESPECIFICA');
CREATE TYPE "ReferenceCircuit" AS ENUM ('PRESCRIPCION_ELECTRONICA', 'HOJA_ELABORACION', 'HISTORIA_CLINICA', 'SISTEMA_FARMACOTECNIA', 'SISTEMA_DISPENSACION', 'OTRO');

ALTER TABLE "Task" ADD COLUMN "taskType" "TaskType" NOT NULL DEFAULT 'GESTION_INTERNA', ADD COLUMN "pseudonymizedReference" TEXT, ADD COLUMN "referenceCircuit" "ReferenceCircuit";
ALTER TABLE "Incident" ADD COLUMN "taskType" "TaskType" NOT NULL DEFAULT 'INCIDENCIA_CIRCUITO', ADD COLUMN "pseudonymizedReference" TEXT, ADD COLUMN "referenceCircuit" "ReferenceCircuit";
